objReader Data/Decimation/triceratops.obj
./gaussMap-single Data/Decimation/triceratops.obj
objReader Data/Demo/triceratops-2500-gm.obj
./gaussMap-single Data/Demo/triceratops-2500-gm.obj
objReader Data/Decimation/venus.obj
./gaussMap-single Data/Decimation/venus.obj
objReader Data/Demo/venus-4000-gm.obj
./gaussMap-single Data/Demo/venus-4000-gm.obj
objReader Data/Demo/venus-8000-gm.obj
./gaussMap-single Data/Demo/venus-8000-gm.obj
objReader Data/Demo/venus-11000-gm.obj
./gaussMap-single Data/Demo/venus-11000-gm.obj
objReader Data/Decimation/rockerarm_small.obj
./gaussMap-single Data/Decimation/rockerarm_small.obj
objReader Data/Demo/rockerarm-9500-gm.obj
./gaussMap-single Data/Demo/rockerarm-9500-gm.obj
